// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pkcuzagkcjwckeipedxh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBrY3V6YWdrY2p3Y2tlaXBlZHhoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzc4MjEzMjUsImV4cCI6MjA1MzM5NzMyNX0.FHwC2LMmedHI_w7DcpgUtArmU8SmyXG8yLVuJBTm62A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);